build: false
clone_folder: c:\projects\fyrye\php-units-of-measure-bundle
clone_depth: 1

cache:
  - composer.phar
  - .phpunit -> phpunit

init:
  - SET PATH=c:\php;%PATH%
  - SET COMPOSER_NO_INTERACTION=1
  - SET SYMFONY_DEPRECATIONS_HELPER=strict
  - SET ANSICON=121x90 (121x90)
  - SET SYMFONY_PHPUNIT_SKIPPED_TESTS=phpunit.skipped
  - REG ADD "HKEY_CURRENT_USER\Software\Microsoft\Command Processor" /v DelayedExpansion /t REG_DWORD /d 1 /f

install:
  - mkdir c:\php && cd c:\php
  - appveyor DownloadFile https://raw.githubusercontent.com/symfony/binary-utils/master/cacert.pem
  - appveyor DownloadFile http://windows.php.net/downloads/releases/archives/php-5.6.28-nts-Win32-VC11-x86.zip
  - 7z x php-5.6.28-nts-Win32-VC11-x86.zip -y >nul
  - del /Q *.zip
  - copy /Y php.ini-development php.ini
  - echo max_execution_time=1200 >> php.ini
  - echo date.timezone="UTC" >> php.ini
  - echo extension_dir=ext >> php.ini
  - echo extension=php_fileinfo.dll >> php.ini
  - echo extension=php_openssl.dll >> php.ini
  - echo extension=php_intl.dll >> php.ini
  - echo extension=php_mbstring.dll >> php.ini
  - echo extension=php_curl.dll >> php.ini
  - echo curl.cainfo=c:\php\cacert.pem >> php.ini
  - cd c:\projects\fyrye\php-units-of-measure-bundle
  - IF NOT EXIST composer.phar (appveyor DownloadFile https://getcomposer.org/download/1.3.0/composer.phar)
  - php composer.phar self-update
  - IF %APPVEYOR_REPO_BRANCH%==master (SET COMPOSER_ROOT_VERSION=dev-master) ELSE (SET COMPOSER_ROOT_VERSION=%APPVEYOR_REPO_BRANCH%.x-dev)
  - php composer.phar update --prefer-dist --no-progress --ansi

test_script:
  - cd c:\projects\fyrye\php-units-of-measure-bundle
  - SET X=0
  - php vendor\bin\phpunit --exclude-group benchmark,intl-data || SET X=!errorlevel!
  - exit %X%
